version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamorm-dynamodb
    ports:
      - "8000:8000"
    volumes:
      - "./storage/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
